### ISSUE TITLE
overcome `system:index` behavior

### ISSUE THREAD

**Issue by fitoprincipe** [gee-community/pytest-gee#43]
**The problem**
When creating a `ee.FeatureCollection` *on-the-fly* GEE creates random values for `system:index` (if were not provided). So, if 2 tables have the same content but were created *on-the-fly*, using the `dataframe_regression` from `pytest-regressions` will fail. Of course we can drop that column in the test, but if we have many tests, we need to do it every time. This proposal is just for reducing the lines of the code and avoid having to think on this in every test.

**Solution**
Inherit `DataFrameRegressionFixture` from `pytest_regressions` and drop the `sytem:index` column before passing to `.check`.

**Comment by 12rambau** [comment]
maybe create a `drop_index` parameter in the existing fixture (ee_feature_collection) ? and if set to True apply your solution.

**Comment by fitoprincipe** [comment]
TBH I didn't consider that fixture, but now that you mentioned it, sounds like the perfect solution ;)
